name: build_release

on: workflow_dispatch

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.1.1
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4.0.0

      - run: pnpm install

      - run: pnpm run build

      - id: version
        run: |
          version=$(node --no-warnings -e "import('@gkd-kit/tools').then(m=>m.stdoutGkdVersion()).then(console.log)")
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Git commit
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --staged --quiet && echo "✅ No changes to commit" && exit 0
          git commit -m "chore: v${{ steps.version.outputs.version }}"

      - name: Git push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body_path: ./dist/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}